### ISSUE TITLE
Snes mini overheating

### ISSUE THREAD

**Issue by alexarus1** [ClusterM/hakchi2#1011] opened 2017-11-06 22:46 UTC
Hi, I wanted to share that I am experiencing possible overheating issues with hakchi 2.21 f.
The case is really hot after 30-45 minutes of usage, and it's something I have never experienced with past releases (I've been sticking with 2.21b).
I also have another snes classic with stock kernel, and after many stress tests, I can say it never gets this hot even after running for 2-3 hours straight.
Thanks for your attention

**Comment by Shoothimnow** [comment] 2017-11-07 00:15
You.... legitimately.... just posted exactly the same thing that the very last (yours is #1011) issue post #1010 said.  Please refer to #966, as they are already aware of this bug.

**Comment by Drakonas** [comment] 2017-11-09 00:10
Closing this as a duplicate of #966. Please keep discussion there for further updates.

**Closed as completed by Drakonas** 2017-11-09 00:10 UTC
Labels: duplicate
