### ISSUE TITLE
Crashes randomly and when you soft reset to menu

### ISSUE THREAD

**Issue by djritz0** [ClusterM/hakchi2#798] opened 2017-10-14 17:44 UTC
2.21c

Randomly crashes when playing snes, nes or genesis Roms. All running off retroarch. Have folder set to 35 games each, with 34 games in each folder. Only modules installed are retroarch, snes9x, genesis, extra space.

When doing soft reset (down+select) goes into blank screen loop for about 1.5 mins (sometimes shorter) and ends up at Main menu and doesn’t create a suspend point.

**Comment by Babbonz** [comment] 2017-10-14 20:16
Yes I also get the random crashes (sometimes I have to pull the power cord out as it completely freezes) when doing soft reset and trying to exit a game?  Ive unistalled retro arch and still get this sometimes just using canoe too?

**Comment by Babbonz** [comment] 2017-10-15 09:15
How do we provide an error log? I've installed hakchi2.21d_debug.zip and the console is crashing quite regularly just using canoe now for me (mostly from randomly doing a soft rest with the pad)  and I'd like to provide the error log (I assume it creates one when it crashes and I somehow can retrieve it when I plug my mini back into my PC)?

**Comment by rsn8887** [comment] 2017-10-15 16:48
I experienced this same error yesterday. I played normally for 10 minutes, but then the console performed a soft reset in the middle of the game. It acted as if I had pressed Select + Down, but I didn't even press Select.

**Comment by ClusterM** [comment] 2017-10-15 16:53
Can you do NAND-C dump using latest version and sent it to me?

**Comment by namedjugheax** [comment] 2017-10-16 13:14
I'm having a similar issue. Flashing the custom kernel seemed to go fine. Now the system can take a few tries to power on. The light will come on, but no picture will come up. Sometimes the SNES classic LED will turn off, and sometimes the light will stay on. Usually after a few tries it will boot, and then will pay games fine. I'm also sometimes having the same issues as the OP when I reset the system. I tried uninstalling Hakchi, and restoring the original kernel, but the issue still persists. I've noticed that the issue is worse if the SNES classic USB is plugged into my TV, but occures less frequently when using the AC adapter.

**Comment by Babbonz** [comment] 2017-10-16 15:47
As the above I've also noticed that using the USB on my tv it crashes more often then using just a USB plug. I hooked my snes mini up yesterday to my PC and the hdmi to my tv (so that I could run and get a debug log) but after playing for more than an hour it didn't crash at all?.. This might just be a coincidence though? I can dump my nand though if this is still required?

**Comment by rsn8887** [comment] 2017-10-16 17:47
It sounds like it might be a power supply problem - not enough current. Try a high current (2 amp) supply.

**Comment by namedjugheax** [comment] 2017-10-16 18:04
I'm currently using a 2.5A power supply for the SNES classic, and still
have the issue. The higher the amps the better, but it doesn't completely
solve the issue. I appreciate the suggestion.

On Oct 16, 2017 1:47 PM, "rsn8887" <notifications@github.com> wrote:

It sounds like it might be a power supply problem - not enough current. Try
a high current (2 amp) supply.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ClusterM/hakchi2/issues/798#issuecomment-336968020>,
or mute
the thread

**Comment by djritz0** [comment] 2017-10-17 12:47
@clusterM

NAND C dump sent to your email. Was a large file so sent as a link.

**Comment by Drakonas** [comment] 2017-10-26 15:30
This user has made 3 tickets for the same issue. Closing this one.

**Closed as completed by Drakonas** 2017-10-26 15:30 UTC

**Comment by abelogan** [comment] 2019-01-10 06:39
I've had this same issue forever. Just now finally realized that decompressing all my ROMs in hakchi2.3.1 seems to have fixed it. Hurrah!
