### ISSUE TITLE
.

### ISSUE THREAD

**Issue by SwagMLG345YT** [ClusterM/hakchi2#1125] opened 2017-12-21 03:15 UTC

**Comment by ghost** [comment] 2017-12-21 03:26
So when you open Hakchi2, it doesn't show the games you added to the console?

Is Hakchi2 recognizing your console is connected to your PC?

**Comment by SwagMLG345YT** [comment] 2017-12-21 03:28
well when i did it. it said that i have to re add the custom kernel even though i did. i’m confused please help.

**Comment by SwagMLG345YT** [comment] 2017-12-21 03:28
oh and also yes it did recognize the console

**Comment by ghost** [comment] 2017-12-21 03:35
The games you added to Hakchi2 are no longer in the "game" folder in Hakchi2's files/folders? Do you keep Hakchi2 on your hard drive, or on a flash drive or CD/DVD? Is the folder you have Hakchi2 in "Read Only"?

**Comment by SwagMLG345YT** [comment] 2017-12-21 04:24
no i'm using a different computer for this.

**Comment by SwagMLG345YT** [comment] 2017-12-21 04:29
and yes not in the games folder

**Comment by gBaH0JI9I** [comment] 2017-12-21 09:07
@SwagMLG345YT 
The answer is: "no i'm using a different computer for this."
You have clean installation of hakchi2 on this computer and asking Why?

**Comment by bslenul** [comment] 2017-12-21 12:39
When you sync games hakchi2 deletes the content of the game folder on your SNESC before uploading. You have to resync every games every time.

In your case the best way to add more games without losing the previously added ones is to add them in hakchi2 but instead of clicking the sync button you manually upload games from `\hakchi2\games_snes` to `/usr/share/games` via FTP.

Anyway, thats not a bug ;)

**Comment by Shoothimnow** [comment] 2017-12-21 14:47
Guys, this isn't a forum.  Hakchi2 is working as expected, please **close this issue** and continue over on a forum... https://www.reddit.com/r/miniSNESmods/

**Comment by ghost** [comment] 2017-12-22 10:55
@SwagMLG345YT when you opened Hakchi2 for the first time on the other PC, you manually added the games to it before syncing to your console. Those games are now part of _that_ build of Hakchi2 on _that_ PC. Unless you copied the entire folder containing Hakchi2 on to a flash drive or other writeable media (CD/DVD) to transfer that entire build to the other computer, as @gBaH0JI9I explained, you are using a clean installation of Hakchi2 on the other PC - a fresh build of the program - and you’ll have to manually add the games to that version of Hakchi2 (even if the console you connect is already modded). Attempting to sync that version of Hakchi2 (without adding the games to it) will remove the games from your console.

If you want to have the same build of Hakchi2 with the same settings and games on another PC, transfer the folder containing Hakchi2 to the other PC by using a flash drive, CD/DVD, or cloud service.

This is not an issue with Hakchi2. Please close this issue report @SwagMLG345YT

**Comment by mrTruch** [comment] 2017-12-25 23:24
Well maybe is an issue not possible to add more games on a new pc....¿? 
I recommend you use hakchi on a USB, is a portable program, and you can clone it on your same PC, any times you want.

Please close this issue report @SwagMLG345YT

**Comment by Shoothimnow** [comment] 2018-01-16 21:40
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

------
As for the thumbs down from mrTruch, this isn't a forum.  This is a place for ClusterM to fix problems.  Not for **us** to explain how to fix a problem.  The fact that he "hacked it again" means to me that he did an uninstall.  He didn't back up the information, and that's not Hachi2's problem.  **This is not something that ClusterM can fix, because it's a user configuration problem**

Regardless, if you think that ClusterM can code you something, mark this issue as a **Request / Issue**.  Otherwise, it's a garbage post that shouldn't belong here

**Closed as completed** 2018-02-02 00:59 UTC
