### ISSUE TITLE
USB read error: IotTimeOut

### ISSUE THREAD

**Issue by Safad0** [ClusterM/hakchi2#642] opened 2017-10-10 18:22 UTC
I keep getting this error when trying to dump the kernel.

**Comment by reverte** [comment] 2017-10-10 18:24
already update to (internal version 2.0.21.32)?

**Comment by joetheuseless** [comment] 2017-10-10 21:39
same problem what do we do when i install the driver it says Nes mini not found even though i can see it in device manager

**Comment by Drakonas** [comment] 2017-10-26 18:22
This has to do with using Ryzen most likely (duplicate of #620) as many tickets have already been made for that. Closing. If you are not on Ryzen, try different USB ports. This is not a Hakchi bug, but a system limitation dealing with power.

**Closed as completed by Drakonas** 2017-10-26 18:22 UTC
Labels: duplicate
