### ISSUE TITLE
snes mod shutting down while playing 

### ISSUE THREAD

**Issue by paty6510** [ClusterM/hakchi2#919] opened 2017-10-23 19:12 UTC
I just modded my snes classic and when im playing games or browsing games it shuts off on me randomly I only put the snes roms with hakchi

**Comment by Drakonas** [comment] 2017-10-23 21:01
make sure you're using the original cable that came with the SNES and plugging it either into a wall or directly into a computer, not a monitor/TV or console or USB hub. Try different usb ports on your computer. Basically, your SNES is not getting the power it needs.

**Comment by paty6510** [comment] 2017-10-25 17:58
system worked fine until I modded it, tried plugging into wall and same thing. the system restarts 2 times while the power is on and then nothing, I followed syndrome208 tutorial any suggestions?

**Comment by Drakonas** [comment] 2017-10-25 18:16
How many snes games did you install?

**Comment by paty6510** [comment] 2017-10-25 18:17
300


Sent from Yahoo Mail for iPhone


On Wednesday, October 25, 2017, 2:16 PM, 3rdN3rd <notifications@github.com> wrote:


How many snes games did you install?

**Comment by Drakonas** [comment] 2017-10-25 18:20
Then you installed way too many. lol Cut that down by 3x the amount and try again.

**Comment by paty6510** [comment] 2017-10-25 18:21
It was at 255.3 and I’m allowed 257.7 mb 


Sent from Yahoo Mail for iPhone


On Wednesday, October 25, 2017, 2:20 PM, 3rdN3rd <notifications@github.com> wrote:


Then you installed way too many. lol Cut that down by 2/3's and try again.

**Comment by Drakonas** [comment] 2017-10-25 18:22
Then the system has no room for save files. lol. You need to leave at least half the free space open for the SNES to use for other things.

**Comment by paty6510** [comment] 2017-10-25 18:23
Okay what’s the best way to go about taking the games off?


Sent from Yahoo Mail for iPhone


On Wednesday, October 25, 2017, 2:22 PM, 3rdN3rd <notifications@github.com> wrote:


Then the system has no room for save files. lol. You need to leave at least half the free space open for the SNES to use for other things.

**Comment by Drakonas** [comment] 2017-10-25 18:23
Uncheck them in Hakchi and resync.

**Comment by paty6510** [comment] 2017-10-25 18:24
Cool thank I will let you know if that works


Sent from Yahoo Mail for iPhone


On Wednesday, October 25, 2017, 2:23 PM, 3rdN3rd <notifications@github.com> wrote:


Uncheck them in Hakchi and resync.

**Comment by Drakonas** [comment] 2017-10-25 18:26
If it doesn't you may need to uninstall hakchi altogether, perform a factory reset (will erase all your saves, but clear out residual data) and try again. Not sure if the SNES Classic has enough room to do anything. You've filled up all the memory. It's like filling up all the storage on a computer. It will have a hard time doing anything.

**Comment by paty6510** [comment] 2017-10-25 18:27
I see people on the web putting that many games so I figured it would have worked 


Sent from Yahoo Mail for iPhone


On Wednesday, October 25, 2017, 2:26 PM, 3rdN3rd <notifications@github.com> wrote:


If it doesn't you may need to uninstall hakchi altogether, perform a factory reset (will erase all your saves, but clear out residual data) and try again. Not sure if the SNES Classic has enough room to do anything. You've filled up all the memory. It's like filling up all the storage on a computer. It will have a hard time doing anything.

**Comment by Drakonas** [comment] 2017-10-25 18:31
Maybe Atari games, but SNES games are like 20x as large. Save files use anywhere from 500KB to 2MB per save, sometimes more..... so it probably would just shut off when it tried to save because it didn't have room. It's generally smart to leave half the space free.

**Comment by Drakonas** [comment] 2017-10-26 15:09
@paty6510 did you ever get this resolved?

**Comment by paty6510** [comment] 2017-10-26 16:47
I did not. I put it back to stock and works fine, gonna wait and see if they come up with a better way or something 


Sent from Yahoo Mail for iPhone


On Thursday, October 26, 2017, 11:09 AM, 3rdN3rd <notifications@github.com> wrote:


@paty6510 did you ever get this resolved?

**Comment by Drakonas** [comment] 2017-10-26 16:49
To be honest, most random shut offs are caused by not providing enough power to the console. The console needs more power with Hakchi installed. Have you tried other USB ports or using different power adapters? This issue needs to be closed if you are done with trying as it is not really a Hakchi bug.

**Comment by paty6510** [comment] 2017-10-26 19:48
I did try different power cords and adaptors I will shut this issue down


Sent from Yahoo Mail for iPhone


On Thursday, October 26, 2017, 12:49 PM, 3rdN3rd <notifications@github.com> wrote:


To be honest, most random shut offs are caused by not providing enough power to the console. The console needs more power with Hakchi installed. Have you tried other USB ports or using different power adapters? This issue needs to be closed if you are done with trying as it is not really a Hakchi bug.

**Comment by Drakonas** [comment] 2017-10-26 20:55
just in case I would try a full factory reset. Backup your saves while hakchi custom kernel is installed (save state manager in hakchi menu, a factory reset will erase all saves), then uninstall hakchi from the hakchi menu, flash og kernel afterwards (if you get MD5 checksum errors then your og kernel dump is corrupted and you need to obtain an untouched one from an unmodified snes or from the internet), then after that perform a full factory reset from the SNES Classic main menu. THIS WILL ERASE ALL SAVES. Then you should go to your hakchi folder and delete all folders EXCEPT games_snes, user_mods, and dump (NEVER DELETE OR LOSE THE DUMP FOLDER). Then, download the latest 2.21f version released within the last hour, and extract it overwriting everything in your Hakchi directory. This will give you a fresh Hakchi setup, but your games are still there. Load up Hakchi, flash custom kernel, and reselect your games' checkmarks and resync your games.

**Comment by Drakonas** [comment] 2017-10-26 20:56
A factory reset will remove all leftover files from bad/old hakchi installs. Most people coming from older versions have problems until they do the full factory reset after uninstall and og flash.

**Comment by paty6510** [comment] 2017-10-27 00:26
With my this is the 1st time trying to install hakchi, so I did have the newest version. It’s just real odd that it has done that makes no since to me I will try what you said and let you know 


Sent from Yahoo Mail for iPhone


On Thursday, October 26, 2017, 4:56 PM, 3rdN3rd <notifications@github.com> wrote:


A factory reset will remove all leftover files from bad/old hakchi installs. Most people coming from older versions have problems until they do the full factory reset after uninstall and og flash.

**Comment by paty6510** [comment] 2017-10-27 01:12
I found this I’m wondering if this is my problem! Look at the troubleshoot! I’m gonna try it tomorrow and I will let you know



Sent from Yahoo Mail for iPhone


On Thursday, October 26, 2017, 4:56 PM, 3rdN3rd <notifications@github.com> wrote:


A factory reset will remove all leftover files from bad/old hakchi installs. Most people coming from older versions have problems until they do the full factory reset after uninstall and og flash.

**Comment by Drakonas** [comment] 2017-10-31 19:28
Have you found the problem @paty6510 ?

**Comment by Drakonas** [comment] 2018-02-07 15:39
Closing this as there has been no response for 3 months.

**Closed as completed by Drakonas** 2018-02-07 15:39 UTC
