### ISSUE TITLE
Sega Genesis command line

### ISSUE THREAD

**Issue by snessy7** [ClusterM/hakchi2#697] opened 2017-10-11 18:13 UTC
Most MD/Genesis ROMs (that I see) are in .bin file format.  When adding to hakchi (2.20, 2.21) the command line command generated is "/bin/bin" which of course does not work.  Always has to be manually modified to "/bin/md" and then they work fine (on SNES Classic with retroarch).  A few ROMs in .md format are correctly detected and use correct "/bin/md" command, just need to consider a fix for .bin files.

**Comment by andyderuyter** [comment] 2017-10-11 18:41
Rename files so they have .md as extension?

**Comment by snessy7** [comment] 2017-10-11 18:48
That might work, but I don't think its any easier than just modifying the command line in hakchi, since the import roms are already zipped up.  Just thought its something hakchi could handle maybe, so I or anybody else don't have to think about it.

**Comment by andyderuyter** [comment] 2017-10-11 18:56
Well, you can always unzip everything (use 7zip, select all zips, right-click the option to unpack them al in the current directory), then mass-rename through command: http://www.thewindowsclub.com/batch-rename-files-extensions-windows

Why unzip? Hackhi removes the 'outer zip-layer' from the game you try to sync, so it can zip it himself using 7zip before transferring it to the console.

Just a suggestion.

**Comment by Drakonas** [comment] 2017-10-26 17:20
The problem is you need to get proper roms @snessy7, which always have .md as the extension. Use No-intro sets. Have you fixed this since then?

**Comment by snessy7** [comment] 2017-10-30 18:42
I haven't bothered any more, I just manually change command to md for Genesis bin roms and it works fine.

**Closed as completed** 2017-10-30 18:43 UTC
