### ISSUE TITLE
AMD Ryzen fix yet?

### ISSUE THREAD

**Issue by joetheuseless** [ClusterM/hakchi2#728] opened 2017-10-12 14:56 UTC
Has anyone found a fix for USB Errors on Ryzen based computers yet?.

Here is what i have tried so far.

Ran program as Administrator ' Disabled driver enforcement '. Tried using several USB cables disabled Windows 10 virus security disabled UAC installed the driver with Zadig Using USB 2.0 .Now its showing up in device manager  but same problem persists USB error's when flashing the custom kernel but strangely works fine copying the original kernel from the console hmm .

I tried to install the driver but it says No nes mini found sorry even though i ripped my kernel first time i must have tried installing the kernel 15 time so far 👎 

Using Ryzen 1700 and Windows 10

I hope a fix is available soon or solution

<a href="https://ibb.co/dgapWG"><img src="https://preview.ibb.co/ipDMdw/gayy.png" alt="gayy" border="0"></a>

<a href="https://ibb.co/muybBG"><img src="https://preview.ibb.co/b0pSJw/fix_1.png" alt="fix_1" border="0"></a>

<a href="https://ibb.co/bvadQb"><img src="https://preview.ibb.co/c41JQb/fix_2.png" alt="fix_2" border="0"></a>

<a href="https://ibb.co/eoGPyw"><img src="https://preview.ibb.co/jCMrdw/FIX_3.png" alt="FIX_3" border="0"></a>

If anyone has a fix please share it with us :)

Thanks

Joe

**Comment by adamcarter1** [comment] 2017-10-12 15:23
Easy fix... buy an intel.  Obviously.

**Comment by joetheuseless** [comment] 2017-10-12 15:26
So i installed the driver yay but now i have a new error can't connect to device when installing the driver hmm

Update tried latest version same issue

**Comment by ClusterM** [comment] 2017-10-13 09:26
Try debug version and send me log.

**Comment by Joonie86** [comment] 2017-10-13 09:29
I'm not sure why though, ryzen seems to have some issues with USB devices, I noticed that too, though after using the stock cable that came with SNES Mini Classic, and used USB 3.0 port instead of 2.0, it seems to be stable (I use Ryzen 1700 and MSI B350 Tomahawk, and Windows 10 RS3)

**Comment by nicholemattera** [comment] 2017-10-13 12:37
Duplicate of #620 

@ClusterM There is logs in that issue.

**Comment by KB0x** [comment] 2017-10-13 23:15
I'm having similar problems and I'm not on a Ryzen build but Intel. In fact I've tried it on my desktop and laptop, no positive results.

**Comment by KB0x** [comment] 2017-10-13 23:48
Wow, I finally got a good dump. I went to my TV and reset to factory defaults. I plugged it back in and I had a failure. I then put in the USB connector and it clicked into place, suddenly it starts working.

**Comment by phillq23** [comment] 2017-10-14 18:39
I have exact same problem. I have a Ryzen 1700 and can dump the kernel fine and install retroarch, but as soon as I try to add more games, “Can’t write to USB”.

**Comment by ghost** [comment] 2017-10-14 19:09
Guys, do you have a USB Gen 3.1 Type A port on your motherboards, either inside or on the rear?
Try that port, it might need two attempts. I couldn't dump my NAND until I used that port specifically, another standard USB 3.0 port on the rear was capable of dumping the NAND-B partition.

I'm on an Intel system but had the same troubles seen here (not the I/O error) on a laptop and desktop.
I also suggest looking at the rear of your SNES and ensuring the Micro-USB cable is properly inserted, the plastic casing can and does get in the way, it can feel like it's in and even turn on but it isn't in completely, wiggle the connector gently until it clicks.

**Comment by joetheuseless** [comment] 2017-10-15 09:26
Still seems buggy i have tried all the USB ports several times and still no luck i get a funny message now when i try and install the USB Driver 

<a href="https://ibb.co/bUnhLb"><img src="https://preview.ibb.co/ddDNLb/fuck_sake.png" alt="fuck_sake" border="0"></a>

I hope a fix is released soon

**Comment by risus-sardonicus** [comment] 2017-10-20 18:07
I found an awkward but simple solution.
I'm using a Ryzen 1600X with a ASUS Prime B350M-A mainboard and the error kept persisting.
It seems to be related to an unusual USB circuit on the motherboard or driver issue although I never had any problems before.
I thought how about using a USB-3.0 hub and you know what? It works!!!
I use a UGREEN 4port USB3.0 hub 20291 which I bought some time ago on Amazon for about 10€.
Maybe other hubs are working too.

**Comment by Drakonas** [comment] 2017-10-31 19:34
I am closing this as a duplicate of #620 please keep all discussion on that ticket, not this one.

**Closed as completed by Drakonas** 2017-10-31 19:34 UTC
Labels: duplicate
