### ISSUE TITLE
Blank screen with sound for about 10 seconds

### ISSUE THREAD

**Issue by djritz0** [ClusterM/hakchi2#883] opened 2017-10-20 17:17 UTC
2.21e

Turning on the unit you can hear music for about 10 seconds before the picture comes in. Works ok, just annoying to have it not come on at the same time.

**Comment by djritz0** [comment] 2017-10-20 18:16
Figured it out. Had to do with Retroarch not being in a folder from the main screen. Fixed. Boots as normal. Only issue now, that happens with every build, is soft resetting to main screen in game after a few plays. Usually starts to do a black screen loop for about a minute or so then enters main screen again. Unit is usually quite warm at this point. Not sure if this is the reason it starts to crash.

**Comment by Drakonas** [comment] 2017-10-24 04:53
Try a different USB port to see if that helps. Most people are seeing that issue resolved by trying a different port. Basically the SNES may not be receiving enough power.

**Comment by Drakonas** [comment] 2017-10-26 15:15
@djritz0 are you still having problems with this?

**Comment by djritz0** [comment] 2017-10-26 16:53
Yes. I've reset the box to factory by uninstalling hakchi and starting over. Still manages to reset sometimes, but usually after some play time. Not sure if this is related to the soft reset as it's usually initiated by a few soft resets to menu. Then will randomly crash after some gameplay has occurred. Not often, but enough to be annoying. Also when it crashes, takes a few mins to go back to the main menu.

**Comment by Drakonas** [comment] 2017-10-26 16:56
@djritz0 Uninstalling Hakchi doesn't erase everything. You need to backup your saves, perform an uninstall, flash og kernel, then perform a factory reset from the SNES Classic menu (THIS WILL ERASE ALL SAVES). There are probably residual files left over from bad/old hakchi installs causing problems.

**Comment by Drakonas** [comment] 2017-10-26 16:57
By the way your email reply included private phone numbers and other info. You really need to not reply from a business email unless you don't use that signature. :P I redacted the info from your message.

**Comment by Juckov** [comment] 2017-10-31 13:57
Had same issue, last week. I was testing random games on NES mini

**Comment by Drakonas** [comment] 2017-10-31 19:11
@Juckov As I said to @djritz0 These issues can be fixed by performing a proper factory reset. Backup your saves with the Hakchie Save Manager in its Tool Menu, uninstall hakchi through the Hakchi's Kernel -> Uninstall function, flash OG kernel (Making sure there are no MD5 checksum errors, else your dump is corrupted and you need to find an untouched one from the internet (from a non-hacked SNESC)), EDIT[ then perform a factory reset from the SNES Classic main menu. THIS WILL ERASE ALL SAVES, but will clear data from bad/old hakchi installs that cause most of these issues], then with the latest Hakchi2 flash the custom kernel.

**Comment by Drakonas** [comment] 2017-10-31 19:12
Sorry @Juckov correction on the steps: between the OG kernel flash and the flash of the custom kernel, please go to the SNES Classic main menu and perform a factory reset from the options menu. This is the CRITICAL step and will ERASE ALL SAVES, but is necessary to fix everything.

**Comment by Juckov** [comment] 2017-11-01 14:34
I let it be. What I have noticed, is that it happens when resetting the console too often. May be some memory leak or something. 
 And my console is NES mini, hackchi 2.17d

**Comment by djritz0** [comment] 2017-11-01 15:05
@juckov youre correct. After you do too many resets it starts to act up. I think the system is trying to CD create too many save states when that happens and causes the machine to crash. Is there a proper fix for this @clusterm ?

**Comment by Drakonas** [comment] 2017-11-02 14:33
@Juckov why don't you try my instructions instead of shrugging it off.

**Comment by Juckov** [comment] 2017-11-02 14:56
I did that the first time it happened. 
The first time was the worst, and it was error c7 I think. I wanted to see how many saves it can keep. Would start a game, save and to the next one. The error popped up on 15th game, or something like that. So it could be turned on but there was the error on screen. 
So I did uninstall, flashed,  then factory reset, and installed hackchi back. 
But it happened again several times after. Last time I new already the cause and reset it on purpose, about 10 times  
All my games take 293 mb,340 mb in total, so there are about 50 mb free . But it doesn't happen during game, only if resetting too often.

**Comment by Drakonas** [comment] 2017-11-02 14:58
... well then there's your problem probably. you need to leave more free space on it. Most C7/C8's and crashes are caused by not having enough free space on the system. It's like having windows with only 2-5GB free space on your hard drive. It has issues.

**Comment by Juckov** [comment] 2017-11-02 15:05
Thanx, I'll let it like that. 390 games
 I don't even play it just scroll through games during 30 mintes and my free time is over.
But I lent it to my friend for several weeks, he finished about 20 games and didn't complained, so if playing soft it makes no errors.

**Comment by Drakonas** [comment] 2017-11-02 15:08
@djritz0 have you ever tried the full uninstall I mentioned in like 3 different tickets to you, and do you have enough free space on your console? I will close this if you're not willing to try. you need to uninstall through hakchi, flash og kernel, then perform factory reset from SNES Classic main menu. then flash custom kernel making sure you get no MD5 Checksum errors.

**Comment by djritz0** [comment] 2017-11-02 19:37
Tried that. How do you get it so there are no checksum errors?

**Comment by Drakonas** [comment] 2017-11-03 17:18
@djritz0 if you are having checksum errors then that is your problem. You have a corrupted or already hacked original dump in your dump folder (if you ever deleted the dump folder since the first time you ever used Hakchi with your SNES it is no longer an original dump). If you run Hakchi from a new folder without copying the dump folder over it will redump the kernel from the already modified SNES Classic meaning any time it creates the custom kernel it will be modifying an already modified kernel, which almost always results in broken features or errors... You need to find an unmodified kernel dump for your region on the internet and place that in place of the one in your dump folder, and uninstall/flash og kernel again. Don't ask for one here. It is copyrighted content.

**Comment by Juckov** [comment] 2017-11-03 17:26
Indeed I have a hacked version, I'll try this weekend to fix it

**Comment by Juckov** [comment] 2017-11-06 16:08
Ok, so I did all that. Found a good kernel, checked it. Resetting 30 times, no errors. 
After installing hackchi 2.21 f, got the error c7 again. (293 mb occupied), but this time I got back to the menu( no restarting) and was able to start games and reset. I have  reset  a few times, and no errors. 
I should try one more time with more free space

**Comment by Drakonas** [comment] 2017-11-09 00:22
..... @Juckov are you installing the extra_space mod? That's probably your problem. It limits the total save space to 50MB, when all the built in games use usually 2.5MB PER savestate. This feature is meant for when you are installing very small amount of extra games. Uninstall that and remove some games to allow a lot of free space for saves, preferably 100MB or more if you are installing hundreds of games.

**Comment by Drakonas** [comment] 2018-02-07 15:39
Closing this as there has been no response for 3 months.

**Closed as completed by Drakonas** 2018-02-07 15:39 UTC
