### ISSUE TITLE
Possible to Duplicate ROMs in System?

### ISSUE THREAD

**Issue by NotATreoFan** [ClusterM/hakchi2#134] opened 2017-02-20 23:42 UTC
Is there a way to load more than one copy of a game?

For example, I added a Zelda 2 mod, Journey of A Day to the NES Classic. This game is ridiculously hard compared to the original, so I was looking into adding some Game Genie codes for it. But I'd rather leave a clean copy on the system as well, for those who are gluttons for punishment.

Each time I copied the duplicated file over, it would replace the original in the list. I tried programs that could modify the CRC and MD5, verified they were different, but hakchi still saw them as the same game.

For this specific example, I was able to fix it by applying the IPS patch for this game to a different copy of the Zelda 2 ROM, and it added as intended after.

**Comment by bfluryx1234** [comment] 2017-02-21 02:16
What we really need is a hotkey to either turn off/on the game genie parameter or to start the game somehow with it off/on.

I personally wouldn't risk it, but potentially if you are set on trying this out... take a look at the games folder.  In theory, you might be able to add a dummy placeholder game there and then replace the contents of that folder with a duplicate of the Zelda hack.

**Comment by NotATreoFan** [comment] 2017-02-21 19:24
That could be a better workaround that having to patch another copy of the ROM. I'll try it tonight and let you know if it works.

**Comment by R3ntZ** [comment] 2017-02-26 09:02
can't you just rename the rom? i think it will keep both

**Comment by NotATreoFan** [comment] 2017-02-28 23:11
@R3ntZ Tried that, but hakchi somehow recognizes that they are the same game. I was able to resolve it with the workaround suggested by @bfluryx1234 and copy the folder, change the name slightly, and then change all the items inside to match.

**Comment by ClusterM** [comment] 2017-03-18 22:30
#187

**Closed by ClusterM** 2017-03-18 22:30 UTC
