### ISSUE TITLE
[Feature Request] Permanent software/Original kernel upgrade feature 

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#1008] opened 2017-11-06 12:14 UTC
When connecting to NES/SNES 

root@CLOVER:~# cat /etc/issue

gives you the current version installed on the system
---
Upload another software version .hsqs to /var/lib/hakchi/
and then
Type:
root@CLOVER:~# hsqs /var/lib/hakchi/XXXXXXXX.hsqs

gives you the ability to upgrade to the desired version
----
Then type
root@CLOVER:~# cat /etc/issue

and check if the new software version is live on your hardware

---

but this trick isn't permanent
When uninstalling end reverting to original kernel (even a newer official kernel version), it goes back to the factory shipped software version.

There should be great improvements to the system by permanently upgrading both original kernel and installed software, and maybe less versions to deal with when programming Hakchi2

**Comment by madmonkey1907** [comment] 2017-11-06 22:52
while this is already implemented, I'm not sure I should provide instructions to do it. you shouldn't uninstall if you system still boots, and you should never flash original kernel, unless you're going to sell/return it.

**Comment by codex785** [comment] 2017-11-07 07:59
@madmonkey1907
Do you mean there is allready a way to permanently upgrade your system?

**Comment by madmonkey1907** [comment] 2017-11-07 12:38
yes. but all you really need to do is not "uninstall and revert to original kernel". it's that easy.

**Comment by codex785** [comment] 2017-11-07 13:30
@madmonkey1907
Do you think that there is a benefit in upgrading the software?

**Comment by madmonkey1907** [comment] 2017-11-07 17:29
none as far as I can tell. version number is different, but it's unknown if anything else besides version number changed between versions.

**Comment by codex785** [comment] 2017-11-08 08:56
@madmonkey1907 
can you describe the update process for those who are technically capable of doing it?
(this may be out of my capabilities), but sharing the process may help people who want to do it at their own risks.
is this applicable to the SNES and NES?
Thanks a lot

**Comment by Drakonas** [comment] 2018-02-07 17:24
There is no "update process", but what madmonkey explained. probably why he didn't respond. The new versions of Hakchi, as long as you haven't installed any experimental hmods, just upgrades by simply installing the new kernel with the new version of Hakchi (after copying the original kernel to the new folder if you're not using the webinstaller version). It will automatically bring everything up to speed. Closing this as this kind of thing should have been asked on Reddit, not here. This is a place to report bugs that you know the cause of, not posting to find an answer to a problem just to ask for help. https://www.reddit.com/r/miniSNESmods/

**Closed as completed by Drakonas** 2018-02-07 17:24 UTC
