### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by GeorgeJellybean** [ClusterM/hakchi2#674] opened 2017-10-11 00:45 UTC
![exception has been thrown](https://user-images.githubusercontent.com/32662574/31369223-94520292-ad48-11e7-91b5-38ada0fd1c4c.PNG)

I've tried all that I can think of to fix the issue, but every time I try, I get this error after trying to dump the kernel

So now as of v2.21b, I run the debug version and get this
![exception has been thrown2](https://user-images.githubusercontent.com/32662574/31417100-194e8894-adf3-11e7-93b0-0c55f42794a7.PNG)

![exception dos](https://user-images.githubusercontent.com/32662574/31417101-1bdfed64-adf3-11e7-8a77-3f28587de3a8.PNG)

Anybody have any ideas at all??

**Comment by ClusterM** [comment] 2017-10-11 00:57
Why screenshots, not log?

**Comment by GeorgeJellybean** [comment] 2017-10-11 00:58
I can get the log if you'd prefer it

**Comment by ClusterM** [comment] 2017-10-11 01:01
Please try this version, it should be more verbose: http://clusterrr.com/temp/hakchi2.21b_debug.zip

**Comment by GeorgeJellybean** [comment] 2017-10-11 01:03
2.21b_debug is the version I used to get the screenshots. I'll run it and post the error long from the cmd prompt

**Comment by ClusterM** [comment] 2017-10-11 01:25
I compiled this version 23 minutes ago :)

**Comment by GeorgeJellybean** [comment] 2017-10-11 01:26
Okay, I'll try it out and see

**Comment by adamcarter1** [comment] 2017-10-11 02:13
Ahhh, ryzen, thats was your first mistake.

**Comment by Drakonas** [comment] 2017-10-26 18:07
Duplicate of #620 closing.

**Closed as completed by Drakonas** 2017-10-26 18:07 UTC
Labels: duplicate
