### ISSUE TITLE
I tried everything but it doesn't work!

### ISSUE THREAD

**Issue by PlsHelpMeh** [ClusterM/hakchi2#1197] opened 2018-02-10 09:26 UTC
I've been dedicated to adding my favorite games on the system, but it won't let me play them. I inserted games with .SNES and .SFC (also .GBA and .NES) files, typed in the correct information for the game, added the correct compatible modules, and included the extra settings. I don't understand why they won't work. Whenever I select them on the SNES menu, the screen blacks out and returns me to the menu. I rechecked to see if I did anything wrong, and I saw something about flashing a custom kernel, which I did, but it still doesn't work a bit. A LITTLE HELP???!!!

**Comment by Frank-5** [comment] 2018-02-10 21:13
Totally understand. I really enjoy having all my favs on my snes mini 
This isn't a help site.  This is a bug tracker git repo. Not the place to ask this question.  This is not a bug with Hakchi.  You need to close this thread and go ask on the Reddit snes mini forums.

**Comment by Drakonas** [comment] 2018-02-10 21:14
Specifically the mini SNES Mods subreddit. https://www.reddit.com/r/miniSNESmods/ Thanks @Frank-5

**Closed as completed by Drakonas** 2018-02-10 21:14 UTC

**Comment by Frank-5** [comment] 2018-02-10 21:19
No problem.  Just gets frustrating to have to wade through all the "please help me"  posts when trying to get the current status relating to actual bugs!  Thank you !!
