### ISSUE TITLE
Certain games that worked before are not working with the latest Hakchi/ retroarch update

### ISSUE THREAD

**Issue by marcaces** [ClusterM/hakchi2#954] opened 2017-10-27 05:55 UTC
Just recently updated to the latest Hakchi2(2.21f) and Retroarch(1.0c) . Now whenever I try to load Terranigma, Illusion Of Gaia, Secret Of Evermore, and Street Fighter Alpha 2 it just loads to a pitch black screen. All these games had worked just fine, with the prior hakchi2, retroarch, and the snesx2010 patch. Now they do not. Wanted to know if anyone else is having this problem and if there was a simple solution to fix it.

**Comment by Drakonas** [comment] 2017-10-27 06:09
Yeah, well, all those games load fine for me in retroarch 1.0c with 2.21f. So this must be a user error. Ask for help with this on the https://www.reddit.com/r/miniSNESmods/ subreddit. Closing this issue as this is not a bug with Hakchi.

**Closed as completed by Drakonas** 2017-10-27 06:09 UTC

**Comment by marcaces** [comment] 2017-10-27 06:27
How did I get a user error?

**Comment by Drakonas** [comment] 2017-10-27 20:48
From Wikipedia: "A user error is an error made by the human user of a complex system, usually a computer system, in interacting with it." The roms work for everyone else just fine, so you must have did something wrong. See the FAQ For reinstallation procedure or ask for help on the subreddit. This is not in our hands.
