### ISSUE TITLE
I have questions about hakchi2

### ISSUE THREAD

**Issue by alEx783** [ClusterM/hakchi2#719] opened 2017-10-12 10:43 UTC
Hi guys,i have some questions about hakchi2 for Snes
I specific that i use and install NOT the web_installer.exe version, but the .zip classic portable version.
So,every time a new  version goes out,i install the .zip classic portable version in a new desktop folder.

1. I have installed extra module 'snes_custom_filters',and then in 'Global command-line arguments' i have written the command line '-no-smooth' (for disable bilinear filter on CRT mode and have scanlines only in all games,included originals).
It works and ok...but if i want to bring  these video options back to their original status,what command line i must write?
I asked it because i have set scanlines only, and after i have tried to unistall extra module  'snes_custom_filters'..but, after that,all  games stop to work...they work only if i reactivate again the extra module  'snes_custom_filters'.
There is an option or command line to reset video option to their factory settings?
2. if i go to kernel/unistall,it remove custom kernel and automatically reinstall original dumped kernel?Or,after unistalled custom kernel,i need to install manually original kernel?
3. If i download new hakchi2.zip classic portable version,how can i transfer into it the roms loaded on previous version of hakchi2?Can i simply copy the folder 'games_snes' from previous to new version of hakchi2?
I have to transfer each times other files/folders from previous to new classic portable version ?Or 'games_snes' folder is enough?Usually i transfer/copy  'games_snes'folder  and 'dump' folder (which contains the original snes kernel dump)
4. The savesgames (and suspend points) of both original and 'added' games where are situated?If i install new hakchi2 version and reinstall to snes all previuos 'added' roms,i will lost savegames?If i reinstall stock kernel?I will losw savegames and suspend points of original games?
5. When i dowload a new version of hakchi2 tool,every time is necessary to click on 'kernel/unistall' and then install  custom kernel ?
6. This morning i have installed custom kernel with latest version of hakchi2 (c2.21c),and when flashing it appears a popup that says : 'MD5 checksum is unknown'..it ask me if i want to continue or not..i press 'yes'..what is this?? It's a problem?It's normal this popup during the installation of a custom kernel?

**Comment by DecanFrost** [comment] 2017-10-12 14:23
For the Md5 error. Remember to flash back to stock first them custom or you will get that wrror

**Comment by alEx783** [comment] 2017-10-12 14:44
Ok,but if i go to kernel/unistall,the program remove custom kernel  and reinstall automatically stock kernel or i need to install manually stock kernel?

**Comment by ClusterM** [comment] 2017-10-12 16:00
Check FAQ please.

**Comment by alEx783** [comment] 2017-10-12 16:11
Where are FAQ?

**Comment by Gardosen** [comment] 2017-10-12 16:50
1 minute of brain using:
https://github.com/ClusterM/hakchi2/wiki/FAQ

**Comment by alEx783** [comment] 2017-10-12 17:47
I have read FAQ,but i didn't found an answer to my question 1).
Maybe the only way for bring back stock filters video options is to reflash original kernel?

**Comment by Drakonas** [comment] 2017-10-26 17:09
The answer to question 1 is to remove the --no-smooth from the command line and resync your games.

**Comment by Drakonas** [comment] 2017-10-31 19:32
Closing this issue as this is not a bug report or feature request. Discussion will be left open. Next time please ask for personal support on reddit or Discord. This is designed to be for reporting bugs or requesting features, not asking questions.

**Closed as completed by Drakonas** 2017-10-31 19:32 UTC
