### ISSUE TITLE
Hakchi + Retroarch = No Demo

### ISSUE THREAD

**Issue by heinrich928** [ClusterM/hakchi2#1009] opened 2017-11-06 14:55 UTC
Demo Mode seems inop. Mario jumps to activate each title, but it does not open, and he moves on  to the next. This happens for all titles he tries.

**Comment by Shoothimnow** [comment] 2017-11-06 15:46
Can you be more specific.  Is this for the default games, or custom games?

--If you are saying that your default 21 games do not have demos, then this is a bug.

--If you are saying that custom installed games do not have demos, there is already a **feature request** #993.  This isn't a bug, as Hakchi2 is working as it's suppose to.  Better explanations can be found how to create these autoplay demos on the Reddit pages and not on the Hakchi2 issues board.

**Comment by heinrich928** [comment] 2017-11-06 15:56
Thanks for replying. More specificity:

Demo does not work with additional games (sounds like a known feature request)
Demo does not work with any games, including stock, when console was last turned off with focus on extra games, and when turned on returns to that sub-menu. Does not work with stock games in this scenario either. If focus is returned to stock menu, demo will begin to work.
Demo does work with stock games when focus is on stock menu (stock games and not extra games)

**Comment by Frank-5** [comment] 2017-11-06 22:35
Exactly what I'm seeing with 2.21f and RetroArch 1.0.

**Comment by Drakonas** [comment] 2017-11-09 00:15
This is not a bug with Hakchi. It is because the SNES Classic requires the game demos to be there for the games. They have to be made. You can make savestates for it to load and make prerecorded games for Canoe games only (will not work with retroarch)

See issue #975 for a tutorial on creating prerecorded game demos yourself. Closing this as it is not an issue with Hakchi, but has to do with Nintendo's design.

**Closed as completed by Drakonas** 2017-11-09 00:15 UTC

**Comment by heinrich928** [comment] 2017-11-09 15:59
Thanks, as long as we know why & how, not having the demos isn't a problem.

**Comment by Drakonas** [comment] 2017-11-10 00:04
@heinrich928 you can have them, but you have to make them. Read my last post's link.
