### ISSUE TITLE
Write error when sync games on version 2.14 and 2.15

### ISSUE THREAD

**Issue by sergiodmn** [ClusterM/hakchi2#250] opened 2017-03-20 12:26 UTC
After uploading the new patched kernel, it starts to upload the games and almost in the beggining an error appears saying "write error".
![image](https://cloud.githubusercontent.com/assets/10518631/24099655/c50d9fc2-0d70-11e7-931d-58318e5d268a.png)

**Comment by DecanFrost** [comment] 2017-03-20 22:32
i had my files in a mod folder and in there a nes folder and then the hakchi folder and i would get write errors after the first write batch, i had to copy the hakchi2 folder to root of drive

**Comment by patoons** [comment] 2017-03-24 02:00
I'm having the same issue as @sergiodmn 

Unfortunately, adding the hakchi2 folder to the root of the drive didn't remedy my issue. Any other potential suggestions?

Thanks.

**Comment by ClusterM** [comment] 2017-03-24 12:58
Please try to reinstall clovershell daemon mod: https://github.com/ClusterM/clovershell-daemon/releases

**Comment by patoons** [comment] 2017-03-25 03:12
Downloaded the clovershell daemon mod, replaced the old clovershell.hmod in the hmod folder, uninstalled all on the nes mini and reinstalled everything again. Same result - 'waiting for the device' and then 'write error'.

Any other potential suggestions / am I missing anything else?

Thank you!

**Comment by ClusterM** [comment] 2017-03-28 22:33
Your "user_mods" folder doesn't contains "clovershell.hmod" file, isn't it?

**Comment by patoons** [comment] 2017-03-29 00:32
That's right, my user_mods folder does not contain the "clovershell.hmod" file.

**Comment by sergiodmn** [comment] 2017-03-29 09:45
Hi @ClusterM I have reinstalled clovershell daemon, as well i've tried to install clovershell via usermods folder, none of them worked :S (running in windows 7 64bits)

**Comment by KMFDManic** [comment] 2017-03-31 11:59
I have found some write errors to be caused by read only attributes.  Unchecking read only on the files that failed to get written to fixes the flashing process.  Other write errors were caused by security permissions, firewall, virus protection.

**Comment by patoons** [comment] 2017-04-02 18:33
Tried again... tried with clovershell in usermods folder. No good.

Then checked security settings. I'm using the admin account and have full control. I've also checked my files and they all have read only unchecked. I turned firewall and antivirus off, as well.

One thing I should mention is I'm operating in Virtualbox - windows 10.

I'm at a wall. No clue wha the issue is. Any other potential suggestions? About ready to give up.

**Comment by Jeffersonmf** [comment] 2017-04-03 10:51
I'm having the same problem.
The Scenario and conditions are exactly the same.
However, I am using Windows 10 through VMware.

**Is this error it because it is in a virtual machine?**

**Comment by KMFDManic** [comment] 2017-04-03 13:50
@jeffersonmf, you have to go into virtual machine usb settings and add it as a device.  Then, follow the rest of the standard process.

**Comment by KMFDManic** [comment] 2017-04-03 13:52
You guys have to add as a device in virtual box, etc settings, so that the drivers can install and enable fel/new mode. Add as device while in fel mode, and also while powered on if possible.

**Comment by sergiodmn** [comment] 2017-04-04 10:30
Anyone was able solve this in vmware virtual machine?

**Comment by KMFDManic** [comment] 2017-04-04 16:10
Yes, the last post I made is the solution, hehe.

**Comment by sergiodmn** [comment] 2017-04-04 17:34
@KMFDManic you mention virtualbox not vmware, it still does not work for me

**Comment by KMFDManic** [comment] 2017-04-04 17:51
To connect USB human interface devices (HIDs) to a virtual machine, you must configure the virtual machine to show all USB input devices in the Removable Devices menu.  This should not matter, whether you are on virtual box, or Vmware.  The main thing is, you HAVE to properly add it as a device, in order for it to be recognized and able to be used by hakchi2 for the flashing process.  Have you attempted to use 2.13e, by chance?  That is a reliable go to hakchi2 for those who have difficulty with 2.14 and 2.15.

**Comment by patoons** [comment] 2017-04-05 03:01
Great, thanks for all the help @KMFDManic! Worked like a charm. Appears my issue was the Driver Signature Enforcement and adding the device in the virtualbox settings.

Thanks again!

**Comment by sergiodmn** [comment] 2017-04-05 08:41
@KMFDManic I have the usb device connected to the virtual machine, I had no problems with previous versions with my VM has Windows 7 in the past. I have disabled driver signature enforcement, no antivirus, no firewall, folder in root, original USB cable, no hub...

**Comment by sergiodmn** [comment] 2017-04-05 09:06
@ClusterM this is the exception:
![image](https://cloud.githubusercontent.com/assets/10518631/24698134/e129bdd6-19ef-11e7-9836-f01352bcd486.png)

**Comment by KMFDManic** [comment] 2017-04-05 09:47
@sergiodmn

Yes, but, it being added as a device in 2.13 is different than in 2.14/2.15. Follow these steps exactly.  They work:)

1.  Flash custom kernel in 2.14.  This will make hakchi2 recognize the device on the mac.
2.  Go into virtual box usb settings.
3.  Power on the device normally, not FEL mode.
4.  NOW, you will see the NES Mini pop up as an entirely NEW device.  Add it.
5.  You can now go back to virtual box and synchronize and it will allow you to install the drivers to use 2.14 new flash mode:)

**Comment by sergiodmn** [comment] 2017-04-05 09:49
OMG, I did that already! I'm using ubuntu not mac, i use vmware not virtualbox, the driver was installed successfully

**Comment by KMFDManic** [comment] 2017-04-05 10:01
That doesn't mean the driver installed successfully. That is exactly what it did when I failed on adding it on a Mac.  I am sorry I missed that you already did that. I can confirm my steps do work flawlessly for 2.14 on virtual box.  I have yet to see anyone confirm they have successfully run 2.15 on macs, period.  So, it seems your options are to do a virtual box setup, or hopefully, clusterm can satisfy conditions for it to install properly on your vmware.  Did you also try another usb port?  Again, sorry for the misread of your previous postings.  I would love to see you in action on 2.14!

**Comment by sergiodmn** [comment] 2017-04-05 10:03
It seems that the driver is installed successfully:
![image](https://cloud.githubusercontent.com/assets/10518631/24700610/eee8ec64-19f7-11e7-9630-e29d49f3a4a4.png)

**Comment by KMFDManic** [comment] 2017-04-05 10:04
This should apply to ubuntu, as well.  I wish I had an identical setup to yours so that I could more easily troubleshoot your problem. But, I can tell you right now, the new driver is not installing correctly.

**Comment by KMFDManic** [comment] 2017-04-05 10:06
Again, I got the identical messages about it being successful on 2.14.  But, it still failed to write til I followed the steps I outlined above.  It said the driver was installed. BUT, hakchi2 fails to recognize and honor the device as valid for flashing.

**Comment by sergiodmn** [comment] 2017-04-05 10:07
I will try in another computer later with osx and vmware, anyone with ubuntu+vmware that could test this?

**Comment by KMFDManic** [comment] 2017-04-05 10:07
There is a vendor id conflict with how the device is read in fel mode and new mode.  It reads as two separate devices.  Hakchi2 doesnt like that.  That was the conflict I had to address in my case.

**Comment by KMFDManic** [comment] 2017-04-05 10:10
One thing to keep in mind.  This is important.  2.14 will have max flash capacity of 250mb on 32 bit os and 300mb on 64 bit.  I would only test with 2.14 and get that running first, before attempting to do 2.15.  Lastly, 2.13e is still friggin excellent for a super nice flash on your setup.  Takes longer yes, but it is very reliable.

**Comment by lil-diabo** [comment] 2017-04-05 10:12
Have you tried to install the zadig driver?
http://zadig.akeo.ie/

**Comment by KMFDManic** [comment] 2017-04-05 10:20
Read down on the post about user settings.  Maybe, this needs done so you can use new mode on usb.

Need help installing driver with Zadig on Ubuntu/Linux machine
https://www.reddit.com/r/nesclassicmods/comments/5t5h4p/need_help_installing_driver_with_zadig_on/

It is, in the end, gonna end up being something completely simple or stupid.

Last few I helped were due to digital driver enforcement and read only properties on the config.ini file in config directory!

**Comment by KMFDManic** [comment] 2017-04-07 19:34
@sergiodmn I would like to let you know that I compiled the LATEST hakchi2 from source code, and clusterm did an amazing job cleaning up the code a bit, for memory issues.  It worked flawlessly on a few people's computers who were unable to properly flash with 2.14/2.15!  I am currently testing out 2.15c, with the following fixes...And, thus far, it is friggin amazing.  Memory cleaned up very well!

-Refactoring.
-Rechecking free memory before uploading.
-Very debug mode.
-Translation.
-Increasing timeouts.
-Checking flash free space before uploading only.
-Support for very long file names.

**Comment by motin** [comment] 2017-04-23 17:52
Was getting the same error: "write error" after "Waiting for the device" after starting a game sync (even with no Games other than "Original 30 games" selected).

> @jeffersonmf, you have to go into virtual machine usb settings and add it as a device. Then, follow the rest of the standard process.

This was actually the solution, ie adding the Nintendo usb device filter in the setting. I was selecting the device in the USB popup menu in the lower right section of the virtual box window, and this works for flashing kernels etc, but not to transfer the games without the write error. 

![msedge_-_win10_preview_-_ports_and_msedge_-_win10_preview__running_](https://cloud.githubusercontent.com/assets/793037/25315544/e1c4e1a6-2856-11e7-8f16-1162d8ef1920.png)

Note that both 2.14 and 2.16c works on Mac OSX Sierra, Virtual Box 5.2.20, with this addition to the original instructions on https://toadle.me/2017/02/03/how-to-add-more-games-to-you-nes-mini-classic-using-hakchi2-and-a-mac.html

**Comment by amrayu** [comment] 2017-07-14 20:45
@motin Thanks for adding the screenshot! This solved my issue. I was doing the same thing you were, which was adding the device via the USB popup menu in the bottom taskbar of Virtualbox window. Thanks again!

**Comment by Drakonas** [comment] 2017-10-31 20:51
Closing this as the OP has not responded for a while. Respond if you are still having issues, but I believe this is a USB driver issue with VMs and not able to be fixed by Hakchi.

**Closed by Drakonas** 2017-10-31 20:51 UTC
Labels: testing required, weird

**Comment by onpurpose** [comment] 2018-01-21 15:06
Hi I am one step further, despite of managing devices and filters correctly, I keep getting this write error, spent hours to figure out why, but it doesn't work for me (I'm using hakchi 2.21, virtualbox with windows10)

Does anyone know what I am missing ? thx...
