### ISSUE TITLE
Ransom ware VIRUS AVG 

### ISSUE THREAD

**Issue by mcsconsole** [ClusterM/hakchi2#590] opened 2017-10-09 05:58 UTC
tried installing hakchi2 2.20 web installer and got an avg alert saying its ransomware

![hakchi2](https://user-images.githubusercontent.com/32629970/31326420-c8305fc2-ad12-11e7-85e0-34c6fb8ef84d.jpg)

**Comment by adamcarter1** [comment] 2017-10-09 05:58
AVG is RANSOMWARE!

**Comment by mcsconsole** [comment] 2017-10-09 06:02
hey no jokes its doing its job
this is a serious subject has anyone else had this issue?
the alert was tripped by the file "2600.png"

**Comment by barryvdh** [comment] 2017-10-09 06:53
No, but seems to be about write protection to your Documents folder, where Hakchi2 seems te write some files to (kernel dump, images of games?)

**Comment by adamcarter1** [comment] 2017-10-09 07:31
Let’s see on your desktop i see the utorrent app and something called free downloads. Dude, avg is probably the worst virus scan out there... notorious for slowing your computer down. If you are going to pirate stuff, at least have half the decency of paying for a legit virus scanner. Invest in eset brah! 


Close this, and stop wasting resources posting this

**Comment by DanTheMan827** [comment] 2017-10-09 14:23
I mean, the ransomware detection is doing its job... the problem is that a lot of things write to the documents folder without user interaction and AVG is just giving a false positive in this case...

To put this in perspective, Mac OS sandboxes each app and specifically denies access to any document unless the user has specifically gives it permission...

**Comment by zimmertr** [comment] 2017-10-09 15:52
Try uninstalling AVG.

**Comment by gnadenlos** [comment] 2017-10-09 17:16
Where's the porn folder?

**Comment by Drakonas** [comment] 2017-10-26 18:50
Why are you asking for help from us and not contacting AVG @mcsconsole ? We can't fix this. AVG is incorrectly detecting the program as ransomware.

**Closed as completed by Drakonas** 2017-10-26 18:50 UTC
Labels: invalid
