### ISSUE TITLE
No sound after adding any new games

### ISSUE THREAD

**Issue by Nyner** [ClusterM/hakchi2#748] opened 2017-10-13 03:44 UTC
Hey guys,

After flashing the new kernel and adding games I lose all sound both in the menu and in games, including the original.  After flashing back to the original kernel, everything returns to normal.

Anyone else having this issue?

**Comment by xstussyone** [comment] 2017-10-13 07:24
Same issue here; no sound, tried flashing original kernel as well. No Dice.

**Comment by K4Z1** [comment] 2017-10-13 11:33
I guess unplugging and replugging the hdmi cable doesn't help?

**Comment by xstussyone** [comment] 2017-10-13 14:12
Tried that, same result.

**Comment by abdessamedh** [comment] 2017-10-13 18:32
Same Issue after flashing custom kerne, i tried to flash original kernel and custom kernel on hackchi 2.21b but no result. Can anyone help us please?

**Comment by pascaH** [comment] 2017-10-15 15:18
Try removing the newly added games (just the ones you added that caused the sound problem). I'm not sure but between reverting to 2.21b, not adding those new games, and re-adding all the other ones the problem was fixed for me.

So to recap, I did this:
- uninstall and get a clean folder for hakchi2 (2.21b)
- flash with custom kernel again and install latest version of retroArch
- add all games (without the last ones that I added just before the sound issue) and copy just the cover art from the "games_snes" folder for the added games

This fixed the sound problem for me. Hope it helps.

**Comment by Nyner** [comment] 2017-10-15 20:32
I don't know about everyone else, but for me going back to the original kernel fixes my sound issue.  Everything returns to normal.  It's only when I add the custom kernel that I lose sound.

**Comment by Drakonas** [comment] 2017-10-24 07:15
Sorry accidental press, has this been resolved?

**Comment by marilite** [comment] 2017-10-24 15:34
@abdessamedh Same problem for me. no sound since installation hakchi same thing with original kernel. I would so like to find the sound!!! did you succeed?

**Comment by Drakonas** [comment] 2017-10-24 17:13
Are any of you getting MD5 checksum errors with Hakchi? If you are your kernel dump is corrupted, or was dumped from an already hacked SNESC. You need to find an original unhacked kernel dump if that is the case.

**Comment by marilite** [comment] 2017-10-24 19:18
I agree but I can’t find it? Please help me!

**Comment by Drakonas** [comment] 2017-10-24 19:21
You won't get help from us for this. It is illegal to share copyrighted content. Ask on a private forums or find the nintendo classics discord chat.

**Comment by Drakonas** [comment] 2017-10-24 19:24
This can normally be resolved by backing up saves with Hakchi savestate manager, uninstalling hakchi using the uninstall function from hakchi, flashing og kernel afterwards, and performing a factory reset from the SNES Classic main menu (THIS WILL ERASE ALL SAVEDATA). Closing this issue as it has been 12 days since the OP responded and this is not a bug with Hakchi but user error. Ask on the Hakchi forum thread or ask on Nintendo Classics support for stuff like this. Create new issues if you are still having issues.

**Closed as completed by Drakonas** 2017-10-24 19:24 UTC
