### ISSUE TITLE
I can't save my non-NES games

### ISSUE THREAD

**Issue by ZeldaGeek** [ClusterM/hakchi2#1017] opened 2017-11-08 02:52 UTC
I was able to successfully add about 160 games to my NES Classic. They all work fine as they should. To be specific, I added 30 GameBoy games, 25 GameBoy Color games, 90 NES games, and 18 Sega Master System games. The NES games can use save states like they should, but when I'm done playing a certain game from another console, hitting the reset button will cause it to not save the game. This can be a problem with games I added like Pokemon that's enjoyable of you could save, and I'm not sure if RetroAch will do anything to fix this. In the next update, it would be great if you did something to fix this. Otherwise, your hack is great.

**Comment by Drakonas** [comment] 2017-11-09 00:00
@ZeldaGeek How much free space do you have reported by Hakchi? And did you install the extra_space mod, which is not recommended?

**Comment by ZeldaGeek** [comment] 2017-11-10 12:02
I’m not sure the exact number, because I don’t have my computer with me, but I had a lot of free space. And I didn’t use the extra space mod.

**Comment by ZeldaGeek** [comment] 2017-11-22 02:41
@Drakonas I have 235.1MB left.

**Comment by qurn78** [comment] 2017-11-22 22:56
I'm having the same issue. When you run a non NES game and bring up the retroarch menu, does the system crash? Mine does. If yours does as well, then we have the same issue. I have plenty of space left on my NES classic, and Im using windows 10.

**Comment by Drakonas** [comment] 2017-12-05 03:43
Have you both made sure you only have 30 to 45 games on screen at one time? Over that and the system will start crashing. @qurn78 @ZeldaGeek

**Comment by ZeldaGeek** [comment] 2017-12-06 12:47
Yes, I have only 30 games per folder.

**Comment by Drakonas** [comment] 2017-12-07 15:00
Wait. @ZeldaGeek did you install the extra_space mod? You shouldn't have that much free space with a normal install. The extra_space mod is not recommended because it limits save space to a total of 50MB, which with as many games as you have, is probably full by now with each save taking 1 to 3 MB.

**Comment by Shoothimnow** [comment] 2017-12-07 18:38
I would uninstall everything and restart again (if this issue cannot be reproduced, then that sounds like to me that the install was originally botched)

**Comment by qurn78** [comment] 2017-12-07 23:51
I did not install the free space mod, have under 30 items per folder. I fixed mine, heres what I did. I installed the web installer version, that alone didnt do it. I grabbed the last batch of retro arch cores, and installed them. I also made sure to flash the custom kernel once they were installed. I think the latest version is broken unless you had previous versions of hakchi installed. The lastest version is the first one I ever tried, and so many things went wrong.

**Comment by Shoothimnow** [comment] 2017-12-08 00:11
If you fixed the problem, please **close this issue**.  This isn't a forum

**Comment by Shoothimnow** [comment] 2017-12-12 22:35
I guess I'll just say it again

If you fixed the problem, please **close this issue**.  This isn't a forum.  And in fact, you originally posted in the wrong section, this should have been post IN a forum ( https://www.reddit.com/r/miniSNESmods/ ).

But again, **this issue should be closed**

**Comment by ZeldaGeek** [comment] 2017-12-18 21:45
But the problem wasn’t fixed.

**Comment by Shoothimnow** [comment] 2017-12-18 23:58
So what isnt working?  RetroArch?  This isnt RetroArch's issue thread, this is Hakchi2's.  If you were able to install the games onto the NES Classic via Hakchi2, and you didn't get any errors.... then.... what problem are you having with Hakchi2.... it sounds like you were able to install the kernal flawlessly....  If you are having problems with an hmod (which is NOT Hakchi2...)... then... you are in the wrong issue board...

The problem wasn't fixed because it doesn't belong here...

Here's RetroArch's issue threads - https://github.com/ClusterM/retroarch-clover/issues

I don't have RetroArch installed, so I don't have different systems on my NES Classic.  Hakchi2 is working flawlessly.  If I were to install RetroArch and I have a problem with that specific program (which again is not Hakchi2), I would post in the correct location to try and get it fixed, instead of having the problem in a limbo location where it will never get fixed over here.

Trying to clean up the garbage that shouldn't be in this issue board...

**Comment by qurn78** [comment] 2017-12-19 00:49
Actually I WASN'T able to install it flawlessly. Even though I fixed my saving issue, I still got a checksum error when  installing the kernal. The system works despite that, but having a workaround is not a fix. 

Also, this is not the only issue I've  had.

**Comment by Shoothimnow** [comment] 2017-12-19 00:56
Then how can ClusterM code a Hakchi2 fix for you, mind you, saving savestates from RetroArch is not a Hakchi2 issue (which again, you are _**saying you are having a problem with Hakchi2**_ by posting in this issue board).  If you were able to install the games to your system, how... is... Hakchi2 not working?

The more detailed, the better

Saying compatibility issues with Canoe (Nintendo's emulator) doesn't belong here, as thats Nintendo's emulator, not Hakchi2

Saying compatibility issues with RetroArch (RetroArch emulator) doesn't belong here, as that has it's own issue board.

Saying that you added 100 games to your system, and Hakchi2 decided to die and corrupt your kernal and no games are now found on the system.  So you then reflash the original kernal, and try again, and you get the same corruption everytime you try to sync your games to the NES Classic, that sounds like a Hakchi2 problem.  1 single person having the problem, so probably just a bad install of Hakchi2, so mainly uninstalling everything to deal with Hakchi2 from the NES classic and re-flashing the original kernal, and then finally uninstalling the application Hakchi2 from your PC to start fresh.  But if more and more people have the problem, then we know it's not an isolated incident and a proper code fix is needed as something is wrong if everyone is having the problem.  **That issue deserves to be here, so that ClusterM should code a fix**.

Saying that I am running RetroArch and it's not saving my games, yeah... that's not a Hakchi2 problem, that's a RetroArch problem.  ClusterM can't code you a fix for Hakchi2 to fix RetroArch... RetroArch needs fixed... RetroArch's issue threads - https://github.com/ClusterM/retroarch-clover/issues

But again, the more detail the better

Also mind you, this isnt a forum (like https://www.reddit.com/r/miniSNESmods/ where if you ask a question, they will help you), so the more we stay on topic, the better.

But again, as it stands, this issue doesn't belong here **and should be closed**

**Comment by Drakonas** [comment] 2017-12-19 16:27
This troubleshooting discussion is getting out of hand, and an answer is not being made because this is not a troubleshooting forum, but a place to report finite issues that have been proven to affect everyone. That has not been proven here. Please resort to Reddit to request help @ZeldaGeek @qurn78 . You will get better help there, and they will tell you if you need to actually create an issue here. I see no issue with Hakchi2 as the issues you are having are typical of corrupted Hakchi2 installs and/or corrupted OG kernel dumps and/or improper installation of Hakchi2/modding the SNES Classic.

**Closed as completed by Drakonas** 2017-12-19 16:27 UTC
Labels: can't reproduce
