### ISSUE TITLE
Activating "remove_thumbnails" module introduces UI lag (2.20)

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#499] opened 2017-10-07 22:04 UTC
Using the module labeled "remove_thumbnails", which gets rid of the lower row of mini-carts in the main menu of the system, makes the whole UI take up to 10 seconds to load, while it usually loads within 2 or 3. You can hear the music playing before the UI draws.

I have a total of 57 games, of which 20 are the original packed-in games (one is hidden). All things considered, those are not a lot of games. I doubt that the system has to take its time reading all the games, so that can't be the source of the issue. Besides, if I'm not using that specific module, my SNESC behaves as it should. Putting all games together or separating them in folders doesn't seem to change anything either.

Sorry if this has already been reported. I did a cursory search and found nothing!

**Comment by ajmi982** [comment] 2017-10-07 22:18
Can confirm. Lag to get back to menu is caused by removing thumbnails. Putting thumbnails back returns the game to menu time.to the 1-2 seconds. Definitely a bug. 

Sent from my iPhone. Please pardon any spelling or grammar mistakes. 

On Oct 7, 2017, at 6:04 PM, JoeyRavn <notifications@github.com> wrote:

Using the module labeled "remove_thumbnails", which gets rid of the lower row of mini-carts in the main menu of the system, makes the whole UI take up to 10 seconds to load, while it usually loads within 2 or 3. You can hear the music playing before the UI draws.

I have a total of 57 games, of which 20 are the original packed-in games (one is hidden). All things considered, those are not a lot of games. I doubt that the system has to take its time reading all the games, so that can't be the source of the issue. Besides, if I'm not using that specific module, my SNESC behaves as it should. Putting all games together or separating them in folders doesn't seem to change anything either.

Sorry if this has already been reported. I did a cursory search and found nothing!

**Comment by gromber** [comment] 2017-10-08 00:10
had same problem.

**Comment by ClusterM** [comment] 2017-10-08 00:27
I know. I don't know why and how to fix. It's internal problem of UI.

**Comment by ghost** [comment] 2017-10-08 08:44
Ouch. That's a pity. IMO having all the games in the same screen without the small icons below them was the best way to organize your games.

**Comment by Drakonas** [comment] 2017-10-31 20:17
This was fixed in a build since. Closing.

**Closed as completed by Drakonas** 2017-10-31 20:17 UTC
Labels: wontfix
