### ISSUE TITLE
I can't connect with mi mac with virtual box.

### ISSUE THREAD

**Issue by yamil02** [ClusterM/hakchi2#333] opened 2017-04-22 20:02 UTC
I'm trying to add more games to my nes but its impossible. I have a Mac with Virtual box and windows 10 installed. I'm doing the same of this page https://toadle.me/2017/02/03/how-to-add-more-games-to-you-nes-mini-classic-using-hakchi2-and-a-mac.html .

I could install hackchi2 without problem, and the same with the controller to use nes in the computer. 
But when i'm connecting  nes with the hakchi2 to do the dump kernel said error. You can show the error here:
![captura de pantalla 2017-04-22 a las 21 47 54](https://cloud.githubusercontent.com/assets/27900534/25307742/a88b3350-27a6-11e7-93a1-d59fffc2497e.png)

Anybody can help me? I tried with wine, parallels and boot camp...and nothing...

Thanks so much. And sorry for my english.

Im looking forward

**Comment by ClusterM** [comment] 2017-04-23 08:15
Seems like some virtualization problem, virtual PC can't access USB device. Probably duplicate of #318.
Maybe some Mac user can help... @KMFDManic ?

**Comment by KMFDManic** [comment] 2017-04-23 09:51
You have to go into virtual box usb settings and add the nes as a device twice.  Once while in FEL mode.  And, once while it is powered on.

**Comment by yamil02** [comment] 2017-04-23 12:48
I added both device, when its powered reconocized like Nintendo Co... and when is in FEL mode like Onda (unverified), here a pic: I'm trying adding device twice but nothing...
The steps are...?? 
1- install device powered
2-install device in fee mode.
3-open hakchi2
4-dump kernel, in this moment I must disconnected the nes and do the steps that hakchi say, right?? 
If i don't disconnect the nes hakchi don't start the dump kernel....
Its ok the steps? or I need to install 2.14 like you said in the #318 ???
![captura de pantalla 2017-04-23 a las 14 42 20](https://cloud.githubusercontent.com/assets/27900534/25313671/6b3bb500-2833-11e7-963f-8f4556a4ba3b.png)

Thanks so much for the help!!!!

**Comment by KMFDManic** [comment] 2017-04-23 13:19
Looks like u should be ok.  To dump the kernel, do not disconnect the mini.  Just hold power and reset same time, releasing reset after 4 seconds or so.  You can also try hakchi2 2.13e, to at least get things going.  Once you succeed there, you would just upgrade directly to 2.16.

**Comment by yamil02** [comment] 2017-04-23 13:21
I could do!!! thanks so much for the help! to did the dump kernel i need do with the nes in fel mode, and when this finish i needed disconnected the nes and connect in powered mode to uploading the game, cause the hakchi said that. now i have 68 games!! I'm going to find more games and the retro arc!!

**Comment by KMFDManic** [comment] 2017-04-23 13:37
Awesome!

**Closed** 2017-05-16 21:04 UTC
