### ISSUE TITLE
Sound sync issue with SNES Classic custom kernel.

### ISSUE THREAD

**Issue by Timedye** [ClusterM/hakchi2#853] opened 2017-10-18 03:50 UTC
So I've got an odd issue and I can't seem to find an answer for it.

When I flash the custom kernel onto the system and test it out, everything is fine. However, the problem starts once I shut the console off. The next time I turn it back on, the sound is two to three seconds out of sync in both the system menus and in games. Turning it off and on again does not help, the sound remains two to three seconds out of sync. This effects all games, both custom and standard. It also doesn't matter if there are custom games installed or not, the issue still arises.

The only way to fix it is to flash the original kernel back onto the box, at which point the issue goes away entirely until I flash the custom kernel again, at which point it resurfaces after the first time I shut it down.

Anyone else had this issue?

**Comment by Timedye** [comment] 2017-10-18 18:38
To further elaborate: I've now tried flashing the system with multiple versions of hakchi, and the result is always the same: the custom kernel causes the sound to fall out of sync after rebooting the system, but restoring the original kernel always fixes it.

I just got my SNES Classic in the mail yesterday, so it's from a new batch of stock. I wonder if something in the kernel has changed somehow since the first wave went out? Just a guess.

**Comment by Timedye** [comment] 2017-10-19 21:35
I seem to have worked out the issue on my own, so I'll post the solution just in case anyone else ends up having this problem.

The problem was caused by one of two issues -- or perhaps a combination of both -- and that was the extension USB cable I was using to run the SNES Classic to the back of my PC, or the USB port that the extension cable was connect to.

I ended up having to spin the computer around -- not an easy task where I keep my PC mounted -- unhooking one of my external HDDs from a USB 3.0 port, and hooking the SNES Classic directly in through that.

I still had some weirdness while flashing the system, but once I got everything set up properly, the sound sync issue after reboot was no longer a thing. I can only assume that something about the 2.0 ports on my PC (or maybe the extender cable mixed with the 2.0 ports) was causing the custom kernel not to flash/install correctly.

So if anyone else ends up having this issue, try using different cables/ports on your PC.

**Comment by Timedye** [comment] 2017-10-20 20:14
So it turns out the issue is not fixed: after booting the SNES Classic up this morning, the sound delay his re-manifested out of the blue. Really at my wits end with this, particularly since I've put a lot of time into Super Metroid now and if I have to flash back to the original kernel again, I'm going to lose my gameplay. :(

**Comment by Drakonas** [comment] 2017-10-24 05:30
You might try doing a full uninstall, og kernel flash and factory reset from the SNES Classic main menu (THIS WILL ERASE ALL SAVES, so backup before you uninstall the custom kernel if you need to!) to remove all residual files left over from bad hakchi installs. And make sure you're not getting any MD5 checksum errors during flashing.

**Comment by Timedye** [comment] 2017-10-26 02:39
Thanks for the tips, Drakonas.

I didn't realize that the "Uninstall" option was for removing hakchi from the SNES Classic, I thought it was to uninstall it from the computer, so I assumed that flashing the original kernel to the system also removed hakchi files from the SNES Classic.

I've just followed the steps you suggested, and so far I've managed to reboot the system a few times without the sound falling out of sync. I'll give it a couple of days (since last time it didn't occur until two days after flashing the system) and I'll report back.

**Comment by Timedye** [comment] 2017-10-26 09:18
Problem re-manifested this morning. I played some SNES roms, NES roms, and GBA roms without incident. Fooled around in a bunch of different games for about an hour. Then I powered the system down, waited about 30 seconds, powered it back on, and the sound is out of sync with the video again. And this in spite of doing a system reset and a fresh re-install of hakchi. Sigh.

**Comment by Timedye** [comment] 2017-10-26 09:21
Incidentally, no checksum errors during flashing. No errors of any kind, so far as I can tell.

**Comment by Timedye** [comment] 2017-10-26 09:37
So, after some fiddling around, it appears to be a problem with how the SNES Classic fires up through my Sony TV. I have my surround sound (which acts as a pass-through for my computer, PS4, and satellite box) plugged into HDMI 1, and the SNES Classic plugged into HDMI 2.

If I boot the SNES Classic up with the TV set to HDMI 2, the sound is out of sync no matter what I do. But if I boot the system up with the TV set to HDMI 1 (or even turned off), then wait for the system to boot up before swapping to HDMI 2 (or turning the TV on), the sound works fine.

I've been able to successfully recreate the sound sync issue 100% of the time by turning the SNES Classic on with the TV already set to the HDMI port that the SNES Classic is connected to, and I've been able to successfully avoid the issue (thus far) by turning the system on with the TV off or set to a different HDMI port. I've tried different HDMI ports, different HDMI cables, and even running the SNES Classic through my surround sound pass-through. Makes no difference.

Very weird, particularly since it doesn't affect the system if a custom hakchi kernel isn't installed. But I suppose if all I have to do is fire the system up first and then turn on the TV or swap to HDMI 2, that's not so bad.

**Comment by Drakonas** [comment] 2017-10-26 14:20
@Timedye you need to try plugging the SNES Classic into some other power source. The port is probably not providing enough power. The problem is not the HDMI most likely.

**Comment by Timedye** [comment] 2017-10-26 21:43
I've just tried plugging it into a different wall outlet, and running it through a couple of different surge protectors as well. The situation remains the same: if I boot the system up with the TV set to whichever HDMI port the SNES Classic is connected to, the sound is out of sync. Turning off the TV or booting the system up on a different HDMI port fixes it.

**Comment by Drakonas** [comment] 2017-10-26 22:20
@Timedye You probably have a corrupted install. Seems like you need a full reset. Backup your saves while hakchi is installed (save state manager in hakchi menu), then uninstall hakchi from the hakchi menu, flash og kernel afterwards (if you get MD5 checksum errors then your og kernel dump is corrupted and you need to obtain an untouched one from an unmodified snes or from the internet), then after that perform a full factory reset from the SNES Classic main menu. THIS WILL ERASE ALL SAVES. Then you should go to your hakchi folder and delete all folders EXCEPT games_snes, user_mods, and dump (NEVER DELETE OR LOSE THE DUMP FOLDER). Then, download the latest 2.21f version released within the last hour, and extract it overwriting everything in your Hakchi directory. This will give you a fresh Hakchi setup, but your games are still there. Load up Hakchi, flash custom kernel, and reselect your games' checkmarks and resync your games.

**Comment by Timedye** [comment] 2017-10-26 23:59
I did all of that last night. I'll try it again later tonight with 2.21f, I guess, but aside from it being different from 2.21b (which I used last night for the first time due to the Yoshi's Island issues with 2.21e) I dunno what difference it will make. But as I say, I'll give it a go.

**Comment by Drakonas** [comment] 2017-10-27 00:03
You factory resetted after uninstalling and flashing og kernel?

**Comment by Timedye** [comment] 2017-10-27 00:19
Yessir.

**Comment by Drakonas** [comment] 2017-10-27 00:36
Well hopefully 2.21f helps.

**Comment by Timedye** [comment] 2017-10-27 01:35
I followed your exact order of operations with 2.21f, but the problem persists. But so long as I turn on the SNES Classic before turning on the TV or swapping to the HDMI port it's plugged into, the issue doesn't manifest. So now it's just an annoyance as opposed to making the system completely unplayable with hakchi installed.

It has to be something to do with my (nearly 10 year old) TV. I dunno what, but that's the only thing I can figure. I'll try to connect it to a friend's (newer) TV later this week and see what happens.

**Comment by TheSuperGents** [comment] 2017-10-28 21:45
It could totally be the TV. Don't have a solution, but I can say I had the same problem and also have a 10-yrs Sony Bravia. I couldnt figure out why and uninstalled and reinstalled Hakchi to no success. I've given up on it for now. 

Hopefully they fix it. Or I may just move my unit to another TV.

**Comment by Drakonas** [comment] 2017-10-29 21:33
If you have a 10 year old TV it probably does not support the resolution the SNES Classic runs in. That is not fixable by Hakchi @Timedye sorry to say. Closing this.

**Closed as completed by Drakonas** 2017-10-29 21:33 UTC
