### ISSUE TITLE
All games added through hakchi go to black screen

### ISSUE THREAD

**Issue by Goodemen** [ClusterM/hakchi2#953] opened 2017-10-26 23:58 UTC
So I followed all the steps to for adding modules and games to my snes classic, the modules I added were Retroarch, genesis_plus_gx, gambattle, mgba, and snes9x2010. Then I added a list of games for each system aside from the original 21 already on the snes classic. All of this went over fine however anytime I attempt to boot up any of the games that aren't one of the original 21 loaded onto the snes classic I get a black screen for a moment then am taking back to the game select screen. This has become a very trying issue and I'm unsure of how to fix it, can any of you help with this?

**Comment by Drakonas** [comment] 2017-10-27 00:02
You probably put way too many games. It's recommended to use only about 60% of the space for games and leave the rest for saves (which also use the space).. also if you are showing all the games in one list that is your problem. The SNES Classic can only handle up to 60 games in one folder.

**Comment by hoderer** [comment] 2017-10-27 00:15
@Drakonas: Strange - I have 7 folders with 100+ games in it for different systems (in some folders are even more games). I installed the extra_space mod to send the save files to the unused 50mb partition and never had problems. I have 900 games on it and about 6MB of free space and everything's fine. the only thing I recognized is the shutdown C8 error. It's easy to prevent when you a) shut down while in a game or b) shutdown when in root folder (where the folders for my systems are). When I do this, I don't have a single problem. I read over and over that it's not good to put more than 30-40 games in one folder, but I don't really get why... I'm really happy that everything is working fine so far.

**Comment by Drakonas** [comment] 2017-10-27 00:39
.... *facepalm* if you have 6MB of free space there is no space for saves.... this is a user error. saves use anywhere from 150KB to 2.4MB per savestate.. and you just limited all your saves to a total of 50MB. Uninstall the extra_space hack and limit your roms to using 60% of the available total space. Obviously it is not "working" if you are having issues. It's like having only 2GB of free space on your windows computer. The machine will crash all the time. The C8 error is caused by not having enough free space. If you deny doing what I have recommended, I'll close this issue as this isn't a Hakchi bug at that point.

**Comment by arimwilson** [comment] 2017-10-28 00:13
I have this same problem but I only added 15 games to my system and they're all SNES games that should work with the native emulator. None of the new games open and my folder only contains 36 games.

EDIT: Sorry my problem was using an old ROM set. No Intro ROMs worked fine.

**Comment by gBaH0JI9I** [comment] 2017-10-28 12:16
**Goodemen**
Sometimes Hakchi don't recognise rom and put in command line /bin/bin
It's wrong. 
For NES should be /bin/nes
For Sega Genesis - /bin/md
And so on.
![default](https://user-images.githubusercontent.com/13234037/32134297-e84f761e-bbf2-11e7-9915-d2cad7adcd66.png)

**Comment by Drakonas** [comment] 2017-10-29 21:51
Closing this as this is not a Hakchi problem, but user error. And the OP has not responded in 3 days. Respond if you wish to keep this open.

**Closed as completed by Drakonas** 2017-10-29 21:51 UTC
